full_list_of_exercises = {
    "Chest Muscles": [
        "Push-ups",
        "Wide grip push-ups",
        "Narrow grip push-ups",
        "Clap push-ups",
        "One-arm push-ups",
        "Diagonal push-ups",
        "Incline push-ups (feet elevated)",
        "Decline push-ups (hands elevated)",
        "Plyometric push-ups",
        "Clap push-ups behind the back",
        "Push-ups with a pause at the bottom",
        "Arm swings to the side while lying on the back",
        "Scissors with arms (lying on the back)",
        "Horizontal flyes on the floor",
        "Floor press with body weight",
        "Finger push-ups",
        "Dips (if available)",
        "One-arm push-ups against the wall",
        "Plank pause with arms spread",
        "Horizontal arm movements in a plank position (swings)"
    ],
    "Back Muscles": [
        "Pull-ups with an underhand grip (if a bar is available)",
        "Wide grip pull-ups",
        "Narrow grip pull-ups",
        "Towel pull-ups (if available)",
        "Superman (lying on the stomach)",
        "Boat pose on the stomach",
        "Arm raises in the boat position",
        "Simultaneous arm and leg lifts (superman)",
        "Plank with an extended arm",
        "Plyometric jump back",
        "Boat pose with arm spreads",
        "Pullover in the boat position",
        "Knees to chest push-ups",
        "Forward bends on one leg",
        "Diagonal lifts in the boat position (alternating)",
        "Upper body lifts while lying on the stomach (with a pause)",
        "Cobra pose with raised legs",
        "Wall chair pose (focus on shoulders and back)",
        "Arm spreads in a plank position",
        "Plank with torso twists"
    ],
    "Leg Muscles (Quadriceps, Glutes, and Hamstrings)": [
        "One-leg squats (pistol)",
        "Regular squats",
        "Jump squats",
        "Forward lunges",
        "Backward lunges",
        "Bulgarian lunges",
        "Sumo squats",
        "Reverence squats",
        "Squats with knee lifts",
        "Side lunges",
        "Half-toe squats",
        "Toe squats with a pause",
        "Deep squats",
        "Glute bridge",
        "Single-leg glute bridge",
        "Standing calf raises",
        "Jumping in place with a half squat",
        "Lunges with a jump",
        "Single-leg calf raises",
        "Side lunges with a forward bend"
    ],
    "Shoulder Muscles": [
        "Shoulder push-ups (handstand against the wall)",
        "Pike push-ups (inverted V position)",
        "Lateral arm raises while standing",
        "One-arm raise in a plank",
        "Straight arm raises while lying",
        "Shoulder rotations backward",
        "Shoulder rotations forward",
        "Plank pause with arms raised",
        "Overhead arm raises (without weights)",
        "Press box (simulate upward punches)",
        "Overhead press (simulate)",
        "Smooth circular arm movements (standing)",
        "Push-ups with elbows close to the body",
        "Arm rotations to the side in a knee plank",
        "Shoulder raises (simulate shrugs)",
        "Circular arm movements to the side",
        "Plank with arms extended forward",
        "Straight arm raises to the side",
        "Push-ups focusing on shoulders",
        "Standing lateral arm swings"
    ],
    "Arms (Biceps and Triceps)": [
        "Narrow grip push-ups (for triceps)",
        "Reverse grip push-ups (with support)",
        "Bench dips",
        "Pause in the reverse push-up position",
        "Push-ups with knees to elbows",
        "Hammer press (simulate)",
        "Three-part push-ups (with pauses)",
        "Arms adduction and abduction (standing)",
        "Narrow grip pull-ups",
        "Arm raise to shoulder (simulate dumbbell)",
        "Press box (simulate)",
        "Snatch (simulate weight lift)",
        "Arm raises with resistance (palms)",
        "Overhead arm raises",
        "Straight arm curls to shoulders",
        "Arm swings forward and backward",
        "Tricep push-ups on the floor",
        "Reverse push-ups on a chair",
        "Arm circles for biceps",
        "Pose hold on extended arms"
    ],
    "Abs": [
        "Classic crunches",
        "Side crunches",
        "Leg raises while lying down",
        "Reverse crunches",
        "Bicycle crunches",
        "Scissors with legs",
        "Plank",
        "Side plank",
        "Plank with leg raise",
        "Plank with arm raise",
        "V-ups",
        "Upper body lifts",
        "Knees to chest lifts while sitting",
        "Side crunches (lying down)",
        "Fold-up",
        "Double leg raises",
        "Hip raises",
        "Dynamic plank",
        "Mountain climbers",
        "Oblique crunches"
    ]
}

universal_workout = {
    "Chest Muscles": [
        {"exercise": "Push-ups", "sets": 3, "reps": 12},
        {"exercise": "Wide grip push-ups", "sets": 3, "reps": 12},
        {"exercise": "Incline push-ups (feet elevated)", "sets": 3, "reps": 10},
        {"exercise": "Decline push-ups (hands elevated)", "sets": 3, "reps": 10},
        {"exercise": "Dips (if available)", "sets": 3, "reps": 8},
        {"exercise": "Horizontal flyes on the floor", "sets": 3, "reps": 12}
    ],
    "Back Muscles": [
        {"exercise": "Pull-ups with an underhand grip", "sets": 3, "reps": 8},
        {"exercise": "Wide grip pull-ups", "sets": 3, "reps": 6},
        {"exercise": "Superman (lying on the stomach)", "sets": 3, "reps": 15},
        {"exercise": "Plank with an extended arm", "sets": 3, "reps": 30},
        {"exercise": "Upper body lifts while lying on the stomach", "sets": 3, "reps": 12},
        {"exercise": "Cobra pose with raised legs", "sets": 3, "reps": 15}
    ],
    "Leg Muscles (Quadriceps, Glutes, and Hamstrings)": [
        {"exercise": "Regular squats", "sets": 3, "reps": 12},
        {"exercise": "Forward lunges", "sets": 3, "reps": 10},
        {"exercise": "Glute bridge", "sets": 3, "reps": 15},
        {"exercise": "Jump squats", "sets": 3, "reps": 10},
        {"exercise": "Bulgarian lunges", "sets": 3, "reps": 8},
        {"exercise": "Standing calf raises", "sets": 3, "reps": 15}
    ],
    "Shoulder Muscles": [
        {"exercise": "Pike push-ups", "sets": 3, "reps": 10},
        {"exercise": "Lateral arm raises while standing", "sets": 3, "reps": 12},
        {"exercise": "Overhead arm raises (without weights)", "sets": 3, "reps": 12},
        {"exercise": "Push-ups with elbows close to the body", "sets": 3, "reps": 10},
        {"exercise": "Plank pause with arms raised", "sets": 3, "reps": 30},
        {"exercise": "Shoulder rotations backward", "sets": 3, "reps": 15}
    ],
    "Arms (Biceps and Triceps)": [
        {"exercise": "Narrow grip push-ups (for triceps)", "sets": 3, "reps": 10},
        {"exercise": "Bench dips", "sets": 3, "reps": 10},
        {"exercise": "Reverse push-ups on a chair", "sets": 3, "reps": 10},
        {"exercise": "Arm raises with resistance (palms)", "sets": 3, "reps": 12},
        {"exercise": "Overhead arm raises", "sets": 3, "reps": 12},
        {"exercise": "Tricep push-ups on the floor", "sets": 3, "reps": 10}
    ],
    "Abs": [
        {"exercise": "Classic crunches", "sets": 3, "reps": 15},
        {"exercise": "Leg raises while lying down", "sets": 3, "reps": 12},
        {"exercise": "Plank", "sets": 3, "reps": 30},
        {"exercise": "Bicycle crunches", "sets": 3, "reps": 15},
        {"exercise": "V-ups", "sets": 3, "reps": 10},
        {"exercise": "Mountain climbers", "sets": 3, "reps": 15}
    ]
}
